Rationale for Financial Analysis: Nigerian Crude Oil Dataset

1. Why We are Using This Dataset
Crude oil is the cornerstone of the Nigerian economy, accounting for the vast majority of foreign exchange earnings and a significant portion of the national budget. This specific dataset provides a granular monthly view of:

Price Volatility: Global market price fluctuations.

  * Operational Output: Volume of oil produced domestically (domProd).

  * Trade Dynamics: The volume of oil sent to the international market (crudeOilExp).

  * By using this data, we are analyzing the primary engine of Nigeria's macroeconomic stability.

By using this data, we are analyzing the primary engine of Nigeria's macroeconomic stability.

2. The Purpose of the Analysis

The primary goal is to transform raw production and price figures into actionable financial insights. Specifically, we aim to:

  * Revenue Modeling: Estimate gross export revenues by combining price and export volume.

  * Trend Identification: Spot cyclical patterns in production and identify periods of significant growth or decline.

  * Correlation Assessment: Determine how domestic production levels respond to global price changes.

  * Forecasting: Evaluate the projected data (up to 2026) to understand future fiscal expectations and potential budget deficits or surpluses.

3. Why This is Beneficial

Performing this analysis offers several strategic advantages:

  * Informed Decision Making: Provides a data-backed foundation for discussing fiscal policy, subsidies, and infrastructure investment.

  * Risk Management: Helps identify the economy's sensitivity to "price shocks" in the global market.

  * Efficiency Tracking: By comparing domProd (Total Production) vs crudeOilExp (Exports), we can infer domestic consumption patterns and the efficiency of the value chain.

  * Economic Predictability: For investors and policy-makers, understanding these trends reduces uncertainty regarding Nigeria's future dollar liquidity and sovereign credit strength.

In [1]:
# import packages
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# import the dataset
df = pd.read_csv(r"C:\Users\ACER\Desktop\Portfolios\crudeoil\Crude_Oil_Data.csv")

In [3]:
# check few rows of the dataset
df.head()

,tyear,tmonth,period,crudeOilPrice,domProd,crudeOilExp
0,2026,2,2/1/2026,72.33,1.31,0.86
1,2026,1,1/1/2026,68.05,1.46,1.01
2,2025,11,11/1/2025,65.22,1.44,0.99
3,2025,10,10/1/2025,66.15,1.40,0.95
4,2025,9,9/1/2025,70.20,1.39,0.94


In [4]:
# Transform 'period' to datetime format
df['period'] = pd.to_datetime(df['period'])
df.head()

,tyear,tmonth,period,crudeOilPrice,domProd,crudeOilExp
0,2026,2,2026-02-01,72.33,1.31,0.86
1,2026,1,2026-01-01,68.05,1.46,1.01
2,2025,11,2025-11-01,65.22,1.44,0.99
3,2025,10,2025-10-01,66.15,1.40,0.95
4,2025,9,2025-09-01,70.20,1.39,0.94


In [5]:
# Calculate daily export revenue in millions of USD
df['daily_rev'] = df['crudeOilPrice'] * df['crudeOilExp']

print(f"Mean Daily Revenue: ${df['daily_rev'].mean():.2f}M")
print(f"Max Daily Revenue: ${df['daily_rev'].max():.2f}M")
print(f"Min Daily Revenue: ${df['daily_rev'].min():.2f}M")

Mean Daily Revenue: $116.28M
Max Daily Revenue: $245.25M
Min Daily Revenue: $22.71M


In [6]:
# Financial risk metrics
price_std = df['crudeOilPrice'].std()
price_mean = df['crudeOilPrice'].mean()
coeff_of_variation = (price_std / price_mean) * 100

print(f"Price Volatility (Std Dev): ${price_std:.2f}")
print(f"Risk Coefficient (CV): {coeff_of_variation:.2f}%")

Price Volatility (Std Dev): $24.48
Risk Coefficient (CV): 31.18%


In [7]:
# Calculate the percentage of production that is actually exported
df['export_ratio'] = (df['crudeOilExp'] / df['domProd']) * 100

print(f"Average Export Efficiency: {df['export_ratio'].mean():.2f}%")

Average Export Efficiency: 75.07%


In [8]:
# Aggregate revenue by year and calculate growth rate
yearly_rev = df.groupby('tyear')['daily_rev'].mean()
yoy_growth = yearly_rev.pct_change() * 100

print("Yearly Revenue Growth Rates (%):")
print(yoy_growth.tail())

Yearly Revenue Growth Rates (%):
tyear
2022    20.766911
2023    -7.051697
2024     8.876417
2025    -1.380423
2026    -9.201678
Name: daily_rev, dtype: float64


In [9]:
# Calculating 12-month Moving Averages for smoothing
df['price_sma12'] = df['crudeOilPrice'].rolling(window=12).mean()
df['prod_sma12'] = df['domProd'].rolling(window=12).mean()

# Check latest trend direction
print(df[['period', 'price_sma12', 'prod_sma12']].tail())

        period  price_sma12  prod_sma12
236 2006-05-01    65.669167    2.324167
237 2006-04-01    65.805000    2.337500
238 2006-03-01    65.865000    2.346667
239 2006-02-01    65.978333    2.360000
240 2006-01-01    66.668333    2.382500


In [10]:
# Seasonal Revenue Cycle
df['revenue'] = df['crudeOilPrice'] * df['crudeOilExp']

# Group by month to find seasonal performance
seasonal_performance = df.groupby('tmonth')['revenue'].mean().sort_values(ascending=False)

print("Average Daily Revenue by Month:")
print(seasonal_performance)

Average Daily Revenue by Month:
tmonth
7     121.178575
9     118.792420
8     118.765110
6     117.905710
10    117.486850
5     117.077930
4     116.629540
3     116.105175
2     115.892971
1     113.883848
12    110.850584
11    110.717555
Name: revenue, dtype: float64


In [11]:
# Comparing early 5-year average vs last 5-year average production
early_prod = df[df['tyear'] <= 2010]['domProd'].mean()
recent_prod = df[df['tyear'] >= 2022]['domProd'].mean()

print(f"Structural Decline: {((recent_prod - early_prod) / early_prod) * 100:.2f}%")

Structural Decline: -42.52%


In [12]:
df = df.sort_values('period')
df['monthly_rev_est'] = df['crudeOilPrice'] * df['crudeOilExp'] * 30 # Approx 30 days

# Calculate Cumulative Revenue
df['cumulative_wealth'] = df['monthly_rev_est'].cumsum()

print(f"Total Wealth Generated (Estimated): ${df['cumulative_wealth'].iloc[-1] / 1000:.2f} Billion")

Total Wealth Generated (Estimated): $840.74 Billion


In [13]:
avg_p_2026 = df[df['tyear'] == 2026]['crudeOilPrice'].mean()
avg_e_2026 = df[df['tyear'] == 2026]['crudeOilExp'].mean()

# Calculate impact of +/- $10 price change
price_impact_minus = (avg_p_2026 - 10) * avg_e_2026
price_impact_plus = (avg_p_2026 + 10) * avg_e_2026

print(f"Base 2026 Daily Revenue: ${avg_p_2026 * avg_e_2026:.2f}M")
print(f"Revenue at -$10 Price: ${price_impact_minus:.2f}M")
print(f"Revenue at +$10 Price: ${price_impact_plus:.2f}M")

Base 2026 Daily Revenue: $65.63M
Revenue at -$10 Price: $56.28M
Revenue at +$10 Price: $74.98M


In [14]:
avg_p_2026 = df[df['tyear'] == 2026]['crudeOilPrice'].mean()
avg_e_2026 = df[df['tyear'] == 2026]['crudeOilExp'].mean()

# Calculate impact of +/- 10% volume change
vol_impact_minus = avg_p_2026 * (avg_e_2026 * 0.90)
vol_impact_plus = avg_p_2026 * (avg_e_2026 * 1.10)

print(f"Revenue at -10% Volume: ${vol_impact_minus:.2f}M")
print(f"Revenue at +10% Volume: ${vol_impact_plus:.2f}M")

Revenue at -10% Volume: $59.06M
Revenue at +10% Volume: $72.19M


In [15]:
avg_p_2026 = df[df['tyear'] == 2026]['crudeOilPrice'].mean()
avg_e_2026 = df[df['tyear'] == 2026]['crudeOilExp'].mean()

# Combined shock: -$10 price AND -10% volume
shock_revenue = (avg_p_2026 - 10) * (avg_e_2026 * 0.90)
base_revenue = avg_p_2026 * avg_e_2026
pct_loss = ((shock_revenue - base_revenue) / base_revenue) * 100

print(f"Shock Scenario Revenue: ${shock_revenue:.2f}M")
print(f"Total Fiscal Loss: {pct_loss:.2f}%")

Shock Scenario Revenue: $50.65M
Total Fiscal Loss: -22.82%


In [16]:
avg_e_2026 = df[df['tyear'] == 2026]['crudeOilExp'].mean()

# Minimum revenue threshold
threshold = 50.0 
break_even_price = threshold / avg_e_2026

print(f"Minimum Price to maintain $50M/day: ${break_even_price:.2f}")

Minimum Price to maintain $50M/day: $53.48


In [ ]:
import ollama
import pandas as pd

analysis_summary = """
PROJECT: Nigerian Crude Oil Financial Analysis (2006 - 2026 Forecast)

KEY METRICS:
- Mean Daily Revenue: $116.28M
- Price Volatility: $24.48 (CV: 31.18%)
- Structural Production Decline: -42.52% (Comparing pre-2010 to post-2022)
- Average Export Efficiency: 75.07%
- Cumulative Wealth Generated: $840.74 Billion

2026 FORECAST & RISK:
- Expected Revenue Growth: -9.20% (Declining trend)
- Shock Scenario: A $10 price drop + 10% volume drop results in a 22.82% fiscal loss.
- Break-even Price: $53.48/barrel required to maintain $50M/day revenue.
"""

# 2. Define the prompt for Qwen
prompt = f"""
You are a Senior Economic Advisor specializing in Oil & Gas and Macroeconomics. 
Analyze the following findings from a Nigerian Crude Oil dataset and provide:
1. A summary of the 'Structural Decline' risk.
2. The implications of the 'Shock Scenario' on national budgeting.
3. Two strategic policy recommendations to improve 'Export Efficiency'.

Data Summary:
{analysis_summary}
"""

# 3. Call Qwen via Ollama
try:
    response = ollama.chat(model='qwen2.5:7b', messages=[
        {
            'role': 'user',
            'content': prompt,
        },
    ])

    print("-" * 30)
    print("QWEN ECONOMIC INSIGHTS:")
    print("-" * 30)
    print(response['message']['content'])

except Exception as e:
    print(f"Error connecting to Ollama: {e}")
    print("Ensure Ollama is running and the 'qwen' model is pulled.")

------------------------------
QWEN ECONOMIC INSIGHTS:
------------------------------
### Summary of the 'Structural Decline' Risk

The Nigerian Crude Oil industry is facing significant structural decline, as evidenced by a 42.52% decrease in production from pre-2010 levels to post-2022. This decline can be attributed to several factors including:

1. **Reserves Depletion**: Natural depletion of oil reserves over time.
2. **Technological Obsolescence**: The industry may have lagged behind in adopting new, more efficient drilling and extraction technologies.
3. **Infrastructure Aging**: Older infrastructure and production facilities are less productive than modern ones.
4. **Environmental Regulations**: Stringent environmental regulations can limit the ability to extract oil from certain areas.

The structural decline poses a significant risk for Nigeria's economy, which heavily relies on crude oil exports for revenue generation. If left unaddressed, this trend could lead to reduced government revenues and slower economic growth.

### Implications of the 'Shock Scenario' on National Budgeting

A shock scenario involving a $10 price drop along with a 10% volume reduction results in a substantial fiscal loss of 22.82%. This implies that:

- **Revenue Volatility**: The national budget will face significant unpredictability and instability due to the high volatility in oil prices.
- **Fiscal Risk Management**: The government must develop robust mechanisms to mitigate this risk, such as diversifying the economy and establishing a sovereign wealth fund to buffer against price fluctuations.
- **Emergency Funds**: Increased allocation of funds for emergency response measures when market shocks occur.

For effective budgeting:
1. **Contingency Planning**: Incorporate scenarios like the shock scenario into long-term financial planning.
2. **Reserve Fund Creation**: Develop and maintain a reserve fund that can be tapped during economic downturns caused by oil price volatility.

### Strategic Policy Recommendations to Improve 'Export Efficiency'

To enhance export efficiency, two key policy recommendations are:

1. **Investment in Technology and Infrastructure**:
   - **Upgrade Drilling Equipment**: Invest in modern drilling equipment and technology to increase production rates and reduce operational costs.
   - **Refinement Projects**: Develop or expand oil refining capabilities locally to add value to crude before exporting it. This can help in reducing dependency on exporting unrefined products, which often fetch lower prices.

2. **Streamlining Regulatory Processes**:
   - **Efficient Permitting System**: Simplify and expedite the permitting process for exploration and production activities.
   - **Harmonized Tax Regimes**: Align tax incentives and regulatory frameworks to encourage investment from both domestic and foreign companies.
   
By implementing these strategies, Nigeria can improve its export efficiency and mitigate some of the risks associated with structural decline and oil price volatility.

In [ ]:
from fpdf import FPDF

# Data metrics extracted from the analysis
metrics = {
    "Daily Revenue": "$116.28M",
    "Volatility (Std Dev)": "$24.48",
    "Risk Coeff (CV)": "31.18%",
    "Structural Decline": "-42.52%",
    "Export Efficiency": "75.07%",
    "Total Wealth (06-26)": "$840.74 Billion",
    "2026 Growth Forecast": "-9.20%",
    "Shock Scenario Loss": "22.82%",
    "Break-even Price": "$53.48"
}

class OilReport(FPDF):
    def header(self):
        # Header background - restricted to page width minus margins
        self.set_fill_color(26, 71, 42) # Dark Green
        self.rect(10, 10, 190, 30, 'F')
        
        self.set_y(15)
        self.set_font('Arial', 'B', 18)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'Nigerian Crude Oil Analysis Report', 0, 1, 'C')
        
        self.set_font('Arial', 'I', 10)
        self.cell(0, 5, 'Comprehensive Financial & Operational Review (2006 - 2026 Forecast)', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Data derived from Nigeria_crude_oil_analysis.ipynb', 0, 0, 'C')

    def section_title(self, label):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(26, 71, 42)
        # Gold accent bar
        self.set_fill_color(212, 175, 55) 
        self.cell(2, 8, '', 0, 0, 'L', True) 
        self.cell(0, 8, f' {label}', 0, 1, 'L')
        self.ln(4)

    def metric_row(self, label, value):
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(60, 7, f"{label.upper()}:", 0, 0)
        self.set_font('Arial', 'B', 11)
        self.set_text_color(26, 71, 42)
        self.cell(0, 7, value, 0, 1)

# 1. Initialize PDF with standard margins
pdf = OilReport()
pdf.set_margins(left=15, top=15, right=15) # Standardized margins to prevent cut-off
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=20)

# --- Executive Summary ---
pdf.section_title("Executive Summary")
pdf.set_font('Arial', '', 11)
pdf.set_text_color(0, 0, 0)
summary = (
    "Crude oil remains the cornerstone of the Nigerian economy[cite: 4]. This report analyzes "
    "historical data from 2006 through 2026 forecasts, focusing on price volatility, "
    "production decline, and fiscal sustainability[cite: 4]. The analysis reveals a "
    "significant structural decline in domestic production[cite: 5]."
)
# Using w=0 and multi_cell ensures text wraps within the 15mm margins
pdf.multi_cell(0, 6, summary, align='L')
pdf.ln(4)

# --- Key Metrics ---
pdf.section_title("Key Performance Metrics")
for label, value in metrics.items():
    pdf.metric_row(label, value)
pdf.ln(6)

# --- Structural Decline ---
pdf.section_title("Structural Decline Risk")
pdf.set_font('Arial', '', 11)
decline_text = (
    f"The industry is facing a structural decline of {metrics['Structural Decline']} "
    "when comparing pre-2010 levels to post-2022 averages[cite: 9]. This trend is "
    "primarily driven by field depletion, aging infrastructure, and a slower rate of "
    "technological adoption[cite: 10]."
)
pdf.multi_cell(0, 6, decline_text, align='L')
pdf.ln(6)

# --- Forecast ---
pdf.section_title("2026 Forecast & Shock Analysis")
forecast_text = (
    f"The outlook for 2026 suggests a continuing downward trend in revenue growth "
    f"of {metrics['2026 Growth Forecast']}[cite: 12]. A combined shock (price drop + "
    f"volume drop) would result in a {metrics['Shock Scenario Loss']} fiscal loss[cite: 13]. "
    f"The break-even price to maintain $50M daily revenue is {metrics['Break-even Price']} per barrel[cite: 14]."
)
pdf.multi_cell(0, 6, forecast_text, align='L')
pdf.ln(6)

# --- Strategic Recommendations ---
pdf.section_title("Strategic Recommendations")
pdf.set_font('Arial', 'B', 11)
pdf.cell(0, 7, "1. Infrastructure and Technology Investment", 0, 1)
pdf.set_font('Arial', '', 11)
pdf.multi_cell(0, 6, "Implement local refining projects to add value to crude before export, reducing dependency on raw material price fluctuations[cite: 16].", align='L')
pdf.ln(2)

pdf.set_font('Arial', 'B', 11)
pdf.cell(0, 7, "2. Regulatory Streamlining", 0, 1)
pdf.set_font('Arial', '', 11)
pdf.multi_cell(0, 6, "Simplify permitting processes and align tax regimes to attract both domestic and foreign direct investment (FDI)[cite: 17].", align='L')

# 2. Output the fixed PDF
output_file = "Nigeria_Oil_Analysis_Fixed.pdf"
pdf.output(output_file)
print(f"Fixed PDF generated: {output_file}")